export const menubarData = [
  {
    id: 2,
    name: "FRUIT & VEGETABLES",
    slug: "fruit-vegetable",
    status: "1",
    photo: null,
    subs: [
      {
        id: 3,
        category_id: "2",
        name: "FRUIT",
        slug: "fruit",
        status: "1",
        childs: [
          {
            id: 4,
            subcategory_id: "3",
            name: "LOCAL FRUITS",
            slug: "local-fruit",
            status: "1",
          },
          {
            id: 5,
            subcategory_id: "3",
            name: "IMPORTED FRUITS",
            slug: "importade",
            status: "1",
          },
          {
            id: 6,
            subcategory_id: "3",
            name: "DATES",
            slug: "dates",
            status: "1",
          },
          {
            id: 7,
            subcategory_id: "3",
            name: "REGULAR FRUITS",
            slug: "regular-fruit",
            status: "1",
          },
        ],
      },
      {
        id: 4,
        category_id: "2",
        name: "VEGETABLE",
        slug: "vegetable",
        status: "1",
        childs: [
          {
            id: 1,
            subcategory_id: "4",
            name: "PREMIUM VEG",
            slug: "premium-vegetable",
            status: "1",
          },
          {
            id: 2,
            subcategory_id: "4",
            name: "DRY VEGETABLE",
            slug: "dry-vegetable",
            status: "1",
          },
          {
            id: 3,
            subcategory_id: "4",
            name: "ALL TIME VEGE",
            slug: "all-time-vege",
            status: "1",
          },
        ],
      },
    ],
  },
  {
    id: 1,
    name: "FISH & MEAT",
    slug: "fish",
    status: "1",
    photo: null,
    subs: [
      {
        id: 1,
        category_id: "1",
        name: "FISH",
        slug: "fish",
        status: "1",
        childs: [
          {
            id: 12,
            subcategory_id: "1",
            name: "FROZEN FISH",
            slug: "frozen-fish",
            status: "1",
          },
          {
            id: 13,
            subcategory_id: "1",
            name: "SEA WATER FISH",
            slug: "sea-water-fish",
            status: "1",
          },
          {
            id: 14,
            subcategory_id: "1",
            name: "SWEET WATER FISH",
            slug: "sweet-water-fish",
            status: "1",
          },
        ],
      },
      {
        id: 2,
        category_id: "1",
        name: "MEAT",
        slug: "meat",
        status: "1",
        childs: [
          {
            id: 8,
            subcategory_id: "2",
            name: "MUTTON",
            slug: "mutton",
            status: "1",
          },
          {
            id: 9,
            subcategory_id: "2",
            name: "CHICKEN",
            slug: "chicken",
            status: "1",
          },
          {
            id: 10,
            subcategory_id: "2",
            name: "BIRD",
            slug: "bird-meat",
            status: "1",
          },
          {
            id: 11,
            subcategory_id: "2",
            name: "BEEF",
            slug: "beef-cow",
            status: "1",
          },
        ],
      },
    ],
  },
];
